#!/usr/bin/env node
/* =========================================================
   gen-i18n.mjs — fills in any AR/RU strings that are missing from
   i18n.js by asking the Lingva API (lingva.ml) to translate them.

   Run this after you add a NEW key to the `strings` object in
   script.js. It does NOT overwrite existing translations (so any
   wording you've hand-tuned in i18n.js is safe) — it only reports
   what's missing and, if you pass --write, appends fresh
   Lingva-generated entries for those specific keys.

   Usage:
     node scripts/gen-i18n.mjs             # just show what's missing
     node scripts/gen-i18n.mjs --write     # also patch i18n.js

   Notes:
   - Keys whose English value is a function (e.g. results_count,
     step_of_label, ...) are always skipped — plurals/placeholders
     need a human to write the target-language version, Lingva can't
     translate a JS function. These are listed so you remember to
     add them by hand.
   - Requires Node 18+ (built-in fetch) and network access.
   ========================================================= */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SCRIPT_JS = join(ROOT, "script.js");
const I18N_JS = join(ROOT, "i18n.js");
const LINGVA_BASE = "https://lingva.ml";
const TARGETS = ["ar", "ru"];
const WRITE = process.argv.includes("--write");

function extractStrings(scriptSource) {
  const match = scriptSource.match(/const strings = \{[\s\S]*?\n\};/);
  if (!match) throw new Error("Couldn't find `const strings = {...};` in script.js");
  // Evaluate just this object literal in an isolated context — it only
  // ever contains string/function literals, no external references.
  const sandbox = {};
  vm.createContext(sandbox);
  const script = new vm.Script(`${match[0]}\nstrings`);
  return script.runInContext(sandbox);
}

function extractTranslations(i18nSource) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  const script = new vm.Script(i18nSource);
  script.runInContext(sandbox);
  return sandbox.window.TRANSLATIONS;
}

async function lingvaTranslate(text, target) {
  const url = `${LINGVA_BASE}/api/v1/en/${target}/${encodeURIComponent(text)}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Lingva ${res.status} for "${text}"`);
  const data = await res.json();
  if (!data.translation) throw new Error(`No translation returned for "${text}"`);
  return data.translation;
}

function jsStringLiteral(str) {
  return JSON.stringify(str);
}

async function main() {
  const strings = extractStrings(readFileSync(SCRIPT_JS, "utf8"));
  const translations = extractTranslations(readFileSync(I18N_JS, "utf8"));

  for (const target of TARGETS) {
    const dict = translations[target] || {};
    const missingStrings = [];
    const missingFunctions = [];

    for (const [key, value] of Object.entries(strings)) {
      if (Object.prototype.hasOwnProperty.call(dict, key)) continue;
      if (typeof value === "function") missingFunctions.push(key);
      else missingStrings.push([key, value]);
    }

    console.log(`\n=== ${target.toUpperCase()} ===`);
    if (missingFunctions.length) {
      console.log(`Skipped (function values — translate by hand): ${missingFunctions.join(", ")}`);
    }
    if (!missingStrings.length) {
      console.log("Nothing missing.");
      continue;
    }

    const generated = {};
    for (const [key, value] of missingStrings) {
      try {
        generated[key] = await lingvaTranslate(value, target);
        console.log(`  ${key}: ${jsStringLiteral(generated[key])}`);
      } catch (err) {
        console.warn(`  ${key}: FAILED (${err.message}) — leave for manual translation`);
      }
    }

    if (WRITE && Object.keys(generated).length) {
      let i18nSource = readFileSync(I18N_JS, "utf8");
      const marker = target === "ar" ? "  ar: {" : "  ru: {";
      const insertion = Object.entries(generated)
        .map(([k, v]) => `    ${k}: ${jsStringLiteral(v)}, // generated by scripts/gen-i18n.mjs — review wording`)
        .join("\n");
      i18nSource = i18nSource.replace(marker, `${marker}\n${insertion}`);
      writeFileSync(I18N_JS, i18nSource);
      console.log(`Patched i18n.js with ${Object.keys(generated).length} new ${target} entries.`);
    }
  }

  if (!WRITE) {
    console.log("\n(Run again with --write to insert these into i18n.js.)");
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
